const products = JSON.parse(`[
    {
        product_id:1,
        name:"Guitar1",
        type_id:1,
        product_price:7900,
        product_detail:"กีตาร์สำหรับคนหล่อเท่วัวตายควายล้ม",
        user_id:12,
        product_img:"./img/guitarthird.jpg"
    },
    {
        product_id:2,
        name:"Eguitar",
        type_id:2,
        product_price:7900,
        product_detail:"กีตาร์สุดเฟี้ยวฟ้าว",
        user_id:12,
        product_img:"./img/guitarthird.jpg"
    },
    {
        product_id:3,
        name:"Effect",
        type_id:3,
        product_price:7900,
        product_detail:"อะไรวะ",
        user_id:12,
        product_img:"./img/guitarthird.jpg"
    },
    {
        product_id:4,
        name:"Amp",
        type_id:4,
        product_price:7900,
        product_detail:"เกินไปน้องชาย",
        user_id:12,
        product_img:"./img/guitarthird.jpg"
    },
    {
        product_id:1,
        name:"Guitar1",
        type_id:1,
        product_price:7900,
        product_detail:"กีตาร์สำหรับคนหล่อเท่วัวตายควายล้ม",
        user_id:12,
        product_img:"./img/guitarthird.jpg"
    },
    {
        product_id:2,
        name:"Eguitar",
        type_id:2,
        product_price:7900,
        product_detail:"กีตาร์สุดเฟี้ยวฟ้าว",
        user_id:12,
        product_img:"./img/guitarthird.jpg"
    },
    {
        product_id:3,
        name:"Effect",
        type_id:3,
        product_price:7900,
        product_detail:"อะไรวะ",
        user_id:12,
        product_img:"./img/guitarthird.jpg"
    },
    {
        product_id:4,
        name:"Amp",
        type_id:4,
        product_price:7900,
        product_detail:"เกินไปน้องชาย",
        user_id:12,
        product_img:"./img/guitarthird.jpg"
    },
    {
        product_id:1,
        name:"Guitar1",
        type_id:1,
        product_price:7900,
        product_detail:"กีตาร์สำหรับคนหล่อเท่วัวตายควายล้ม",
        user_id:12,
        product_img:"./img/guitarthird.jpg"
    },
    {
        product_id:2,
        name:"Eguitar",
        type_id:2,
        product_price:7900,
        product_detail:"กีตาร์สุดเฟี้ยวฟ้าว",
        user_id:12,
        product_img:"./img/guitarthird.jpg"
    },
    {
        product_id:3,
        name:"Effect",
        type_id:3,
        product_price:7900,
        product_detail:"อะไรวะ",
        user_id:12,
        product_img:"./img/guitarthird.jpg"
    },
    {
        product_id:4,
        name:"Amp",
        type_id:4,
        product_price:7900,
        product_detail:"เกินไปน้องชาย",
        user_id:12,
        product_img:"./img/guitarthird.jpg"
    },
    {
        product_id:1,
        name:"Guitar1",
        type_id:1,
        product_price:7900,
        product_detail:"กีตาร์สำหรับคนหล่อเท่วัวตายควายล้ม",
        user_id:12,
        product_img:"./img/guitarthird.jpg"
    },
    {
        product_id:2,
        name:"Eguitar",
        type_id:2,
        product_price:7900,
        product_detail:"กีตาร์สุดเฟี้ยวฟ้าว",
        user_id:12,
        product_img:"./img/guitarthird.jpg"
    },
    {
        product_id:3,
        name:"Effect",
        type_id:3,
        product_price:7900,
        product_detail:"อะไรวะ",
        user_id:12,
        product_img:"./img/guitarthird.jpg"
    },
    {
        product_id:4,
        name:"Amp",
        type_id:4,
        product_price:7900,
        product_detail:"เกินไปน้องชาย",
        user_id:12,
        product_img:"./img/guitarthird.jpg"
    }
]`)