
// index
var home = new Vue({
        el:'#app',
        data:{
            login_state:false,
            message:"hello world",
            login_username:"",
            login_password:"",
            username:"",
            images:[
                "./img/guitarfirst.jpg",
                "./img/guitarsecond.jpg",
                "./img/guitarthird.jpg"
            ],
            index:0,
            n:1,
            product_type:[
                {
                    id:1,
                    name:"กีตาร์โปร่ง",

                },
                {
                    id:2,
                    name:"กีตาร์ไฟฟ้า",
                    
                },
                {
                    id:3,
                    name:"เอฟเฟค",
                    
                },
                {
                    id:4,
                    name:"แอมป์",
                    
                }
            ],
            selected_pt:0,
            tmp_producted:[
                {
                    product_id:1,
                    name:"Guitar1",
                    type_id:1,
                    product_price:7900,
                    product_detail:"กีตาร์สำหรับคนหล่อเท่วัวตายควายล้ม",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:2,
                    name:"Eguitar",
                    type_id:2,
                    product_price:7900,
                    product_detail:"กีตาร์สุดเฟี้ยวฟ้าว",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:3,
                    name:"Effect",
                    type_id:3,
                    product_price:7900,
                    product_detail:"อะไรวะ",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:4,
                    name:"Amp",
                    type_id:4,
                    product_price:7900,
                    product_detail:"เกินไปน้องชาย",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:1,
                    name:"Guitar1",
                    type_id:1,
                    product_price:7900,
                    product_detail:"กีตาร์สำหรับคนหล่อเท่วัวตายควายล้ม",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:2,
                    name:"Eguitar",
                    type_id:2,
                    product_price:7900,
                    product_detail:"กีตาร์สุดเฟี้ยวฟ้าว",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:3,
                    name:"Effect",
                    type_id:3,
                    product_price:7900,
                    product_detail:"อะไรวะ",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:4,
                    name:"Amp",
                    type_id:4,
                    product_price:7900,
                    product_detail:"เกินไปน้องชาย",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:1,
                    name:"Guitar1",
                    type_id:1,
                    product_price:7900,
                    product_detail:"กีตาร์สำหรับคนหล่อเท่วัวตายควายล้ม",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:2,
                    name:"Eguitar",
                    type_id:2,
                    product_price:7900,
                    product_detail:"กีตาร์สุดเฟี้ยวฟ้าว",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:3,
                    name:"Effect",
                    type_id:3,
                    product_price:7900,
                    product_detail:"อะไรวะ",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:4,
                    name:"Amp",
                    type_id:4,
                    product_price:7900,
                    product_detail:"เกินไปน้องชาย",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                }, {
                    product_id:1,
                    name:"Guitar1",
                    type_id:1,
                    product_price:7900,
                    product_detail:"กีตาร์สำหรับคนหล่อเท่วัวตายควายล้ม",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:2,
                    name:"Eguitar",
                    type_id:2,
                    product_price:7900,
                    product_detail:"กีตาร์สุดเฟี้ยวฟ้าว",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:3,
                    name:"Effect",
                    type_id:3,
                    product_price:7900,
                    product_detail:"อะไรวะ",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:4,
                    name:"Amp",
                    type_id:4,
                    product_price:7900,
                    product_detail:"เกินไปน้องชาย",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:1,
                    name:"Guitar1",
                    type_id:1,
                    product_price:7900,
                    product_detail:"กีตาร์สำหรับคนหล่อเท่วัวตายควายล้ม",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:2,
                    name:"Eguitar",
                    type_id:2,
                    product_price:7900,
                    product_detail:"กีตาร์สุดเฟี้ยวฟ้าว",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:3,
                    name:"Effect",
                    type_id:3,
                    product_price:7900,
                    product_detail:"อะไรวะ",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:4,
                    name:"Amp",
                    type_id:4,
                    product_price:7900,
                    product_detail:"เกินไปน้องชาย",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                }

            ],
             products:[
                {
                    product_id:1,
                    name:"Guitar1",
                    type_id:1,
                    product_price:7900,
                    product_detail:"กีตาร์สำหรับคนหล่อเท่วัวตายควายล้ม",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:2,
                    name:"Eguitar",
                    type_id:2,
                    product_price:7900,
                    product_detail:"กีตาร์สุดเฟี้ยวฟ้าว",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:3,
                    name:"Effect",
                    type_id:3,
                    product_price:7900,
                    product_detail:"อะไรวะ",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:4,
                    name:"Amp",
                    type_id:4,
                    product_price:7900,
                    product_detail:"เกินไปน้องชาย",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:1,
                    name:"Guitar1",
                    type_id:1,
                    product_price:7900,
                    product_detail:"กีตาร์สำหรับคนหล่อเท่วัวตายควายล้ม",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:2,
                    name:"Eguitar",
                    type_id:2,
                    product_price:7900,
                    product_detail:"กีตาร์สุดเฟี้ยวฟ้าว",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:3,
                    name:"Effect",
                    type_id:3,
                    product_price:7900,
                    product_detail:"อะไรวะ",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:4,
                    name:"Amp",
                    type_id:4,
                    product_price:7900,
                    product_detail:"เกินไปน้องชาย",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:1,
                    name:"Guitar1",
                    type_id:1,
                    product_price:7900,
                    product_detail:"กีตาร์สำหรับคนหล่อเท่วัวตายควายล้ม",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:2,
                    name:"Eguitar",
                    type_id:2,
                    product_price:7900,
                    product_detail:"กีตาร์สุดเฟี้ยวฟ้าว",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:3,
                    name:"Effect",
                    type_id:3,
                    product_price:7900,
                    product_detail:"อะไรวะ",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:4,
                    name:"Amp",
                    type_id:4,
                    product_price:7900,
                    product_detail:"เกินไปน้องชาย",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                }, {
                    product_id:1,
                    name:"Guitar1",
                    type_id:1,
                    product_price:7900,
                    product_detail:"กีตาร์สำหรับคนหล่อเท่วัวตายควายล้ม",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:2,
                    name:"Eguitar",
                    type_id:2,
                    product_price:7900,
                    product_detail:"กีตาร์สุดเฟี้ยวฟ้าว",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:3,
                    name:"Effect",
                    type_id:3,
                    product_price:7900,
                    product_detail:"อะไรวะ",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:4,
                    name:"Amp",
                    type_id:4,
                    product_price:7900,
                    product_detail:"เกินไปน้องชาย",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:1,
                    name:"Guitar1",
                    type_id:1,
                    product_price:7900,
                    product_detail:"กีตาร์สำหรับคนหล่อเท่วัวตายควายล้ม",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:2,
                    name:"Eguitar",
                    type_id:2,
                    product_price:7900,
                    product_detail:"กีตาร์สุดเฟี้ยวฟ้าว",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:3,
                    name:"Effect",
                    type_id:3,
                    product_price:7900,
                    product_detail:"อะไรวะ",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                },
                {
                    product_id:4,
                    name:"Amp",
                    type_id:4,
                    product_price:7900,
                    product_detail:"เกินไปน้องชาย",
                    user_id:12,
                    product_img:"./img/guitarthird.jpg"
                }
             ]
                
            ,
        },
        created () {

            setInterval(this.next, 5000)
        },
        methods:{
            showlogin(){
                document.querySelector(".popup").style.display="flex";
            },
            closelogin(){
                document.querySelector(".popup").style.display="none";
            },
            login(){
                this.username = this.login_username;
                this.login_username="";
                this.login_password="";
                document.querySelector(".popup").style.display="none";
               
                this.login_state = true;
                // window.location.href ="index.html";
            },
            next(){
                this.index += 1
                if(this.index > this.images.length - 1){
                    this.index = 0
                }
            },
            log(){
                // test
                console.log('eiei')
            },
            gofavorite(){
                if(this.login_state){
                    window.location.href="favorite.html";
                }
                else{
                    this.showlogin()
                }
            }

        },
        watch:{
            selected_pt(newval){
                if(newval != 0){
                    this.products = this.tmp_producted.filter(value => {
                        return  value.product_id === newval;
             
             })
                }
                else{
                    this.products = this.tmp_producted;
                }
              
            }
        }
    });
    var regis = new Vue({
        el:'.register',
        data:{
            username:'',
            password:"",
            confirmpassword:"",
            email:"",
            phone:'',
        },
        watch:{
        }  
    })
    

